server:
  port: 8082

eureka:
  client:
    registered-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0

department:
  service:
    base:
      url: http://DEPARTMENT-SERVICE/departments/

